# hopemeals/app/pdfs.py
from io import BytesIO
from django.http import HttpResponse
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def allocation_pdf(order, allocations):
    """
    Professional PDF: header, donor-split table, totals, and signature box.
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18*mm, rightMargin=18*mm, topMargin=18*mm, bottomMargin=18*mm
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle('h1', parent=styles['Heading1'], fontSize=16, leading=20, spaceAfter=8)
    h2 = ParagraphStyle('h2', parent=styles['Heading2'], fontSize=12, leading=16, textColor=colors.HexColor("#334155"))
    body = ParagraphStyle('body', parent=styles['BodyText'], fontSize=10, leading=14)

    elems = []

    # Header
    elems.append(Paragraph("HopeMeals – Allocation Note", h1))
    sub = (
        f"<b>Order ID:</b> #{order.id} &nbsp;&nbsp; "
        f"<b>Item:</b> {order.item_name} &nbsp;&nbsp; "
        f"<b>Qty (people):</b> {order.people_count}"
    )
    elems.append(Paragraph(sub, body))
    ngo_line = f"<b>NGO:</b> {order.ngo.username if order.ngo else 'Unassigned'}"
    rx_line = f"<b>Receiver:</b> {order.receiver.username}"
    elems.append(Paragraph(ngo_line + " &nbsp;&nbsp; " + rx_line, body))
    elems.append(Spacer(1, 8))

    # Allocation table
    data = [["#", "Donor", "Donation ID", "Allocated (people)"]]
    total = 0
    for i, a in enumerate(allocations, start=1):
        donor = getattr(a.donation.donor, "username", "-")
        qty = a.quantity
        total += qty
        data.append([str(i), donor, f"#{a.donation.id}", str(qty)])

    tbl = Table(data, colWidths=[10*mm, 60*mm, 30*mm, 35*mm])
    tbl.setStyle(TableStyle([
        ('FONT', (0,0), (-1,0), 'Helvetica-Bold', 10),
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0ea5e9")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,0), 'CENTER'),

        ('FONT', (0,1), (-1,-1), 'Helvetica', 10),
        ('LINEABOVE', (0,0), (-1,0), 1, colors.HexColor("#0ea5e9")),
        ('LINEBELOW', (0,0), (-1,0), 0.5, colors.HexColor("#0ea5e9")),
        ('GRID', (0,1), (-1,-1), 0.25, colors.HexColor("#cbd5e1")),
        ('ALIGN', (-1,1), (-1,-1), 'RIGHT'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
    ]))
    elems.append(tbl)

    # Totals
    elems.append(Spacer(1, 6))
    elems.append(Paragraph(f"<b>Total allocated:</b> {total} people", h2))

    # Signature / stamp box
    elems.append(Spacer(1, 16))
    sig = Table(
        [["NGO Signature/Stamp", "", "Receiver Acknowledgement", ""]],
        colWidths=[45*mm, 35*mm, 55*mm, 35*mm],
        rowHeights=[20*mm]
    )
    sig.setStyle(TableStyle([
        ('BOX', (0,0), (1,0), 0.75, colors.HexColor("#94a3b8")),
        ('BOX', (2,0), (3,0), 0.75, colors.HexColor("#94a3b8")),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('FONT', (0,0), (-1,-1), 'Helvetica', 10),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
    ]))
    elems.append(sig)

    # Footer
    elems.append(Spacer(1, 10))
    elems.append(Paragraph(
        "Generated by HopeMeals • This document serves as a delivery allocation record.",
        ParagraphStyle('foot', parent=styles['BodyText'], fontSize=8, textColor=colors.HexColor("#64748b"))
    ))

    doc.build(elems)
    pdf = buf.getvalue()
    buf.close()

    resp = HttpResponse(pdf, content_type="application/pdf")
    resp["Content-Disposition"] = f'inline; filename="order_{order.id}_allocation.pdf"'
    return resp
